export enum EquipmentProficiency {
  // Armor
  Shields = "Shields",
  LightArmor = "Light Armor",
  MediumArmor = "Medium Armor",
  HeavyArmor = "Heavy Armor",

  // Weapons
  MartialWeapons = "Martial Weapons",
  SimpleWeapons = "Simple Weapons",
  Rapiers = "Rapiers",
  HandCrossbows = "Hand Crossbows",
  Battleaxes = "Battleaxes",
  Handaxes = "Handaxes",
  LightHammers = "Light Hammers",
  Warhammers = "Warhammers",
  Longswords = "Longswords",
  Shortswords = "Shortswords",
  Longbows = "Longbows",
  Shortbows = "Shortbows",
  Greatswords = "Greatswords",
  Morningstars = "Morningstars",
  Flails = "Flails",
  Scimitars = "Scimitars",
  WarPicks = "War Picks",
  Tridents = "Tridents",
  Glaives = "Glaives",
  Greataxes = "Greataxes",
  Halberds = "Halberds",
  Mauls = "Mauls",
  Pikes = "Pikes",
  HeavyCrossbows = "Heavy Crossbows",
  Clubs = "Clubs",
  Daggers = "Daggers",
  Javelins = "Javelins",
  Maces = "Maces",
  Sickles = "Sickles",
  Quarterstaves = "Quarterstaves",
  Spears = "Spears",
  Greatclubs = "Greatclubs",
  Slings = "Slings",
  LightCrossbows = "Light Crossbows"
}

export const MARTIAL_WEAPONS = new Set<EquipmentProficiency>([
  EquipmentProficiency.Morningstars,
  EquipmentProficiency.Flails,
  EquipmentProficiency.Scimitars,
  EquipmentProficiency.Rapiers,
  EquipmentProficiency.Shortswords,
  EquipmentProficiency.WarPicks,
  EquipmentProficiency.Battleaxes,
  EquipmentProficiency.Longswords,
  EquipmentProficiency.Tridents,
  EquipmentProficiency.Warhammers,
  EquipmentProficiency.Glaives,
  EquipmentProficiency.Greataxes,
  EquipmentProficiency.Greatswords,
  EquipmentProficiency.Halberds,
  EquipmentProficiency.Mauls,
  EquipmentProficiency.Pikes,
  EquipmentProficiency.HandCrossbows,
  EquipmentProficiency.HeavyCrossbows,
  EquipmentProficiency.Longbows
]);

export const SIMPLE_WEAPONS = new Set<EquipmentProficiency>([
  EquipmentProficiency.Clubs,
  EquipmentProficiency.Daggers,
  EquipmentProficiency.Handaxes,
  EquipmentProficiency.Javelins,
  EquipmentProficiency.LightHammers,
  EquipmentProficiency.Maces,
  EquipmentProficiency.Sickles,
  EquipmentProficiency.Quarterstaves,
  EquipmentProficiency.Spears,
  EquipmentProficiency.Greatclubs,
  EquipmentProficiency.Slings,
  EquipmentProficiency.LightCrossbows,
  EquipmentProficiency.Shortbows
]);
